config/routes.rb
ActionController::Routing::Routes.draw do |map|
  root :controller => :home,:action => :index  
  # Control Panel 
  namespace 'cpanel' do
    root :controller => :home, :action => :index
    map.login "login", :controller => :home, :action => :login
    map.logout "logout", :controller => :home, :action => :logout

    resources :menus,:pages,:posts,:categories
    resources :settings, :only => [:index, :create] do
      collection do
        get :password
        post :password
        get :profile
        post :profile
      end
    end
  end
  
  # Blog
  resources :blogs, :controller => :posts, :path => "blog" do
    collection do
      get :category, :path => "category/:category", :action => :index
      get :rss    
    end
  end
  
  match "xmlrpc" => "xmlrpc#index"
 
  match "share" => "home#share"
  match "twitter" => "home#twitter"
  match "unfollow" => "home#unfollow"
  map.page ":slug", :controller => :home, :action => :show, :requirements => { :slug => /[a-z0-9A-Z\-\_\.]+/ }
  
  # base routes
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
  
end

app/controllers/cpanel/home_controller.rb
# coding: utf-8 
# admin home controller
class Cpanel::HomeController < Cpanel::ApplicationController
  before_filter :require_login,:only => [:index,:logout]
  
  # cpanel
  def index
    @total = {}
    @total[:post_count] = Post.count
    @total[:page_count] = Page.count

    @recent_posts = Post.limit(5)
  end
  
  # cpanel/logout
  def logout
    clear_login
    redirect_to :controller => "/home", :action => "index"
  end
  
  # cpanel/login
  def login
    @user = User.new
    
    if params[:user]
      @user = User.check_login(params[:user][:uname], User.encode(params[:user][:pwd]))
      if @user
        save_login(@user)
        redirect_to :controller => "/cpanel"
        return
      else
        @user = User.new
        flash[:errors] = "用户名或密码不正确。"
      end
    end
    
    render :action => "login", :layout => false
  end
  
end

app/controllers/home_controller.rb
# coding: utf-8 
class HomeController < ApplicationController
  caches_page :show
  caches_action :share, :cache_path =>  Proc.new { |c| "home/share" }, :expires_in => 1.days
  
  def index
    set_seo_meta(nil,@setting.meta_keywords,@setting.meta_description)
    set_nav_actived("home")

    # get fanfou messages
    if !@setting.twitter_id.blank?
      @tweets = []
      begin
        @tweets = Tweet.gets(@setting.twitter_id,5)
      rescue => e
        logger.error { "Home twitter load failed: #{e}" }
      end
    end
    
    if !fragment_exist? "home/index/recent_posts"
      @recent_posts = Post.publish.limit(13).where(:status => 1)
    end
  end

  def show
    @page = Page.find_show(params[:slug])
    if not @page
      render_404
      return
    end
    set_seo_meta(@page.title)
    set_nav_actived(@page.slug)
    render :file => "pages/show", :layout => "application"
  end
  
  def twitter
    set_nav_actived("twitter")
    set_seo_meta("我的 Twitter")
    @tweets = Tweet.gets(@setting.twitter_id,20)
  end
  
  def share
    set_nav_actived("share")
    set_seo_meta("Google Reader 分享")
    @api_url = Share.api_url(@setting)
    @shares = Share.find_all(@setting)
  end
  
  # unfollow for email notice
  # type  Model
  # id    Model id
  # key   email encode key
  def unfollow
    return render_404  if params[:type].blank? or params[:id].blank? or params[:key].blank?
    email = Encoder.decode(params[:key])
    return render_404 if email.blank?

    Unfollower.create(:email => email, 
                      :unfollowerable_type => params[:type].capitalize, 
                      :unfollowerable_id => params[:id].to_i)
                      
    render :text => "你已经成功退定."
  end
end

app/views/home/error.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
	<title>应用程序异常</title>
	<%= stylesheet_link_tag "src/error", :cache => "error" %>
</head>
<body>
	<div id="main">
		<h1>应用程序异常</h1>
		<div class="box">
			<%= @message %>
		</div>
	</div>
</body>
</html>

app/views/home/index.html.erb
<ul class="archive">
<% cache("home/index/recent_posts") do %>
<% if !@recent_posts.blank?%>
  <% for item in @recent_posts %>
    <li>
      <a href="<%= blog_path(item.slug) %>" title="<%= item.title %>"><%= truncate(item.title, :length => 30) %></a> 
      <span class="date"><%= item.created_at.to_date %></span>
    </li>
  <% end %>
<% end %>
<% end %>
</ul>

 <div id="tweet" class="section">
  <h2>Twitter<a href="/twitter">more</a></h2>
  <%= render "shared/tweets", :items => @tweets %>
</div>

app/views/home/share.html.erb
<%= content_for :styles do %> 
  <link rel="alternate" title="ATOM" type="application/atom+xml" href="<%= @api_url %>">
<% end %>
<div id="shares" class="box">
  <h2>Google Reader 分享</h2>
  <% if !@shares.blank? %>
    <ul>
    <% for item in @shares %>
    <li><a href="<%= item["link"] %>" target="_blank"><%= item["title"] %></a></li>
    <% end %>
    </ul>
  <% end %>	
</div>

app/views/home/twitter.html.erb
<div id="tweet" class="section">
  <h2>Twitter Timeline <a href="http://twitter.com/<%= @setting.twitter_id %>">Follow me</a></h2>
  <%= render "shared/tweets", :items => @tweets %>
</div>