config/routes.rb
ActionController::Routing::Routes.draw do |map|
  root :controller => :home,:action => :index  
  # Control Panel 
  namespace 'cpanel' do
    root :controller => :home, :action => :index
    map.login "login", :controller => :home, :action => :login
    map.logout "logout", :controller => :home, :action => :logout

    resources :menus,:pages,:posts,:categories
    resources :settings, :only => [:index, :create] do
      collection do
        get :password
        post :password
        get :profile
        post :profile
      end
    end
  end
  
  # Blog
  resources :blogs, :controller => :posts, :path => "blog" do
    collection do
      get :category, :path => "category/:category", :action => :index
      get :rss    
    end
  end
  
  match "xmlrpc" => "xmlrpc#index"
 
  match "share" => "home#share"
  match "twitter" => "home#twitter"
  match "unfollow" => "home#unfollow"
  map.page ":slug", :controller => :home, :action => :show, :requirements => { :slug => /[a-z0-9A-Z\-\_\.]+/ }
  
  # base routes
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
  
end

app/views/xmlrpc/rsd.html.erb
<?xml version="1.0" encoding="utf-8"?>
<rsd version="1.0" xmlns="http://archipelago.phrasewise.com/rsd">
  <service>
    <engineName>WordPress</engineName>
    <engineLink>http://github.com/huacnlee/personlab</engineLink>
    <homePageLink><%= root_url %></homePageLink>
    <apis>
      <api name="WordPress" blogID="1" preferred="true" apiLink="<%= xmlrpc_url %>" />
      <api name="Movable Type" blogID="1" preferred="false" apiLink="<%= xmlrpc_url %>" />
      <api name="MetaWeblog" blogID="1" preferred="false" apiLink="<%= xmlrpc_url %>" />
      <api name="Blogger" blogID="1" preferred="false" apiLink="<%= xmlrpc_url %>" />
      <api name="Atom" blogID="" preferred="false" apiLink="" />
    </apis>
  </service>
</rsd>