config/routes.rb
ActionController::Routing::Routes.draw do |map|
  root :controller => :home,:action => :index  
  # Control Panel 
  namespace 'cpanel' do
    root :controller => :home, :action => :index
    map.login "login", :controller => :home, :action => :login
    map.logout "logout", :controller => :home, :action => :logout

    resources :menus,:pages,:posts,:categories
    resources :settings, :only => [:index, :create] do
      collection do
        get :password
        post :password
        get :profile
        post :profile
      end
    end
  end
  
  # Blog
  resources :blogs, :controller => :posts, :path => "blog" do
    collection do
      get :category, :path => "category/:category", :action => :index
      get :rss    
    end
  end
  
  match "xmlrpc" => "xmlrpc#index"
 
  match "share" => "home#share"
  match "twitter" => "home#twitter"
  match "unfollow" => "home#unfollow"
  map.page ":slug", :controller => :home, :action => :show, :requirements => { :slug => /[a-z0-9A-Z\-\_\.]+/ }
  
  # base routes
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
  
end

app/models/post.rb
# coding: utf-8 
require "string_extensions"
class Post < ActiveRecord::Base
  acts_as_taggable_on :tags
  belongs_to :category, :counter_cache => true
  
  validates_uniqueness_of :title, :slug, :case_sensitive => false , :message => "已经有同名的存在,请检查是否重发了."
  validates_presence_of :title,:body,:status
	
  # callback events
  before_validation :safe_slug_validation
  def safe_slug_validation
    self.slug = self.slug.safe_slug
  end
  
  # status
  STATUS = [
    ["请选择状态",-1],
    ["发布",1],
    ["草稿",2],
    ].freeze
  
  # scope
  default_scope :order => 'posts.id desc'
  scope :publish, where(:status => 1)
  
  # string formated created_at
  def created_at_s
    created_at.to_s(:short_date_string)
  end
  
  # body summary
  def summary
    @sumarry_mark = "<!--{/summary}-->"
    if body.index(@sumarry_mark)
      body.split(@sumarry_mark)[0]
    else
      body.truncate_html(250,'')
    end
  end
    
  # cache delayed view_count
  def delay_view_count
    cache_key = "data/posts/view_count/#{slug}"
    Rails.cache.read(cache_key).to_i || 0
  end
  
  def self.update_view_count(slug)
    delay = 10
    cache_key = "data/posts/view_count/#{slug}"
    count = Rails.cache.read(cache_key).to_i || 0
    if count % delay == 0 && count != 0
      post = find_by_slug(slug)
      if post
        post.view_count += count + 1
        Post.where(:id => post.id).update_all(:view_count => post.view_count)
      end
      count = 0
    else
      count += 1
    end
    Rails.cache.write(cache_key,count)  
    count
  end
end

app/controllers/cpanel/posts_controller.rb
# coding: utf-8 
class Cpanel::PostsController < Cpanel::ApplicationController
  cache_sweeper :post_sweeper,:only => [:create,:update,:destroy]
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.paginate(:page => params[:page], :include => [:category])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new
    respond_to do |format|
      format.html { render :action => "edit" }
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        save_notice("文章创建成功,可以 <a href=\"#{blog_path(@post.slug)}\" target=\"_blank\">点击这里</a> 查看")
        format.html { redirect_to :controller => "posts", :action => "index" }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        logger.debug { "post_update" }
        save_notice("文章修改成功,可以 <a href=\"#{blog_path(@post.slug)}\" target=\"_blank\">点击这里</a> 查看")
        format.html { redirect_to :controller => "posts", :action => "index" }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      save_notice("文章删除成功.")
      format.html { redirect_to(cpanel_posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/posts_controller.rb
# coding: utf-8 
class PostsController < ApplicationController
  caches_action :rss, :depends => ["posts_list"]
  caches_action :index,
    :cache_path =>  Proc.new { |c| "blog/index/#{c.request.params[:page]}:#{c.request.params[:category]}:#{c.request.params[:tag]}" },
    :depends => ["posts_list"]
  before_filter :init_posts
  
  private
  def init_posts
    set_nav_actived("blog")
  end
  
  public
  def index		
    page = params[:page] ? params[:page] : 1    
    if params[:category]
			@category = Category.find_by_slug(params[:category])
			if not @category
				render_404
				return
			end
      
      @posts = @category.posts.publish.paginate :include => [:category],:page => page, :per_page => 5
      set_seo_meta("博客 &raquo; 分类：#{@category.name}")        
    elsif params[:tag]    
      @posts = Post.tagged_with(params[:tag]).publish.paginate :include => [:category],:page => page, :per_page => 5
      set_seo_meta("博客 &raquo; Tag:#{params[:tag]}")
    else      
      @posts = Post.publish.paginate :include => [:category], :page => page, :per_page => 5            
      set_seo_meta("博客")
    end
  end


  
  def rss
    # Get the 10 most recent photos
    @posts = Post.publish.paginate :include => [:category], :page => 1, :per_page => 20
    # Title for the RSS feed
    @feed_title = "10 most recent photos"
    # Get the absolute URL which produces the feed
    @feed_url = "http://" + request.host_with_port + request.request_uri
    # Description of the feed as a whole
    @feed_description = "20 most recent posts"
    # Set the content type to the standard one for RSS
    response.headers['Content-Type'] = 'application/rss+xml'
    # Render the feed using an RXML template
    render :action => 'rss', :layout => false
  
  end
  
  def show
    # update pv
    @view_count = Post.update_view_count(params[:id])
    
    @post = Post.publish.where(:slug => params[:id]).includes(:category).first
    if not @post
      return render_404
    end
    
    set_seo_meta(@post.title,@post.meta_keywords,@post.meta_description)   
  end
end

app/helpers/posts_helper.rb
# coding: utf-8 
module PostsHelper
end

app/views/posts/_tags.html.erb
<% cache("posts/#{post.id}:#{post.updated_at.to_i}/tags") do %>
  <% if not post.tags.blank? %>
    <label style="margin-left:20px;">Tags:</label>
    <% for tag in post.tags %>
      <a href="<%= blogs_path(:tag => tag.name) %>"><%= tag.name %></a>
    <% end %>
  <% end %>
<% end %>

app/views/posts/index.html.erb
<div id="content">  
  <% if !@posts.blank? %>
	  <% for item in @posts %>
	    <div class="entry">
	      <h1>
	        <a href="<%= blog_path(item.slug) %>" title="<%= item.title %>"><%= truncate(item.title,:length => 80) %></a>
	      </h1>
	      <div class="date"><a href="<%= category_blogs_path(item.category.slug) %>" title="<%= item.category.name %>"><%= item.category.name %></a> - <%= l item.created_at, :format => :long %></div>
	      <div class="body">
	        <%= raw item.summary %>
	      </div>		
	      <div class="footer"> 
	        <a href="<%= blog_path(item.slug, :anchor => "disqus_thread") %>" title="查看评论" data-disqus-identifier="disqus:huacnlee:posts:<%= item.id %>">Comments</a>,
	        <a href="<%= blog_path(item.slug)%>"><%= item.view_count + item.delay_view_count %> Views</a>
	      </div>
	    </div>		
	  <% end %>	
	  <%= will_paginate @posts %>
	<% else %>
	  <div class="none_result">
	    作者还未发表过文章.
	  </div>
	<% end %>
</div>

app/views/posts/show.html.erb
<div id="content">
  <div class="entry">
		<h1>
      <a href="<%= blog_path(@post.slug) %>" rel="nofollow"><%= @post.title %></a>
		</h1>
		<div class="date">
			<%= link_to (@post.category.name), category_blogs_path(@post.category.slug) %>
      <%= l @post.created_at, :format => :long %>
    </div>    
		<div class="body">
			<%= raw @post.body %>
    </div>    
    <div class="footer">      
			<span class="view_count"><%= @post.view_count + @view_count %> Views</span>, 
			<span class="comment_count"><a href="#disqus_thread" ata-disqus-identifier="disqus:huacnlee:posts:<%= @post.id %>">Comments</a></span>			
      <%= render "tags", :post => @post %>
		</div>
	</div>
  <div id="disqus_thread"></div>
  <script type="text/javascript">
      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
      var disqus_shortname = '<%= @setting.disqus_shortname %>'; // required: replace example with your forum shortname
      var disqus_title = '<%= @post.title %>';
      var disqus_url = '<%= blog_url(@post.slug) %>';
      var disqus_identifier = 'disqus:huacnlee:posts:<%= @post.id %>';

      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>